### PR TITLE
waffle.io Badge

### PR DESCRIPTION
**Pull request by waffle-iron**
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/CPSSD/feedlark

This was requested by a real person (user devoxel) on waffle.io, we're not trying to spam you.

### CODE REVIEW

**Comment by CianLR** [comment]
Did you merge this yourself? Omg. This is not what Stallman died for.

**Comment by devoxel** [comment]
That's a fantastic comment lol. I'm putting that in a new repo I'm working on.

**Comment by iandioch** [comment]
Can we revert this on principle?

**Comment by devoxel** [comment]
Yes.

**Pull request merged**
